name: Convert Notebook to PDF

on:
  push:

jobs:
  export-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc \
                                 texlive-xetex \
                                 texlive-fonts-recommended \
                                 texlive-plain-generic
          pip install nbconvert jupyter

      - name: Convert Notebook to PDF
        run: |
          jupyter nbconvert --to pdf project.ipynb --output project.pdf

      - name: Commit PDF to branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add project.pdf

          short_sha=$(echo "${{ github.sha }}" | cut -c1-7)

          git commit \
            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" \
            -m "Add PDF for commit $short_sha"
          
          git push origin HEAD:${{ github.ref_name }}
