name: Convert Notebook to PDF

on:
  push:

jobs:
  export-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # This ensures we check out the exact branch/ref 
          # that triggered the push event.
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install jupyter

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build PDF
        run: |
          quarto render project.ipynb --to pdf

      - name: Commit PDF to branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add project.pdf

          short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
          git commit -m "Add PDF for commit $short_sha"
          
          git push origin HEAD:${{ github.ref_name }}
